<div class="wrapper">

  {include file="../../../public/static/template/top" /}

  {include file="../../../public/static/template/left" /}

  <div class="content-wrapper">
    <section class="content-header">
      <h1>
        Home
        <small>Home</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Home</li>
      </ol>
    </section>
  </div>

  {include file="../../../public/static/template/footer" /}

  <div class="control-sidebar-bg"></div>

</div>

