
{include file="../../../public/static/template/top" /}

{include file="../../../public/static/template/left" /}

<div class="content-wrapper">
    <section class="content-header">
        <h1>
            Home
            <small>demo</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">demo</li>
        </ol>
    </section>
    <div class="box-body">
        <div class="progress progress-striped active">
            <div id="prog" class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="" aria-valuemin="0" aria-valuemax="100" style="width:0%;">
                <span id="proglabel">正在启动，请稍后......</span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-6">
                <button id="pause" class="btn btn-primary" value="pause">暂停</button>
                <button id="stop" class="btn btn-primary" value="stop">停止</button>
            </div>
        </div>
    </div>
</div>

{include file="../../../public/static/template/footer" /}

<script>
    var value = 0;
    var time = 50;
    //进度条复位函数
    function reset( ) {
        value = 0
        $("#prog").removeClass("progress-bar-success").css("width","0%").text("等待启动");
    }

    function increment(value) {
        $("#prog").css("width",value + "%").text(value + "%");
        if (value>=0 && value<100) {
            $("#prog").addClass("progress-bar-info");
        } else {
            setTimeout(reset,3000);
            return;
        }
    }
</script>
<?php echo str_repeat('',4096); ?>
<?php foreach ($users as $user): ?>
    <?php
        for ($i = 0;$i < 10000; $i++ ){

        }
    ?>
    <script language="JavaScript">
        increment(<?php echo intval($progress); ?>);
    </script>
    <?php flush(); $progress += $pix; ?>
<?php endforeach; ?>

<script language="JavaScript">
    //最后将进度条设置成最大值 $width，同时显示操作完成
    increment(<?php echo $width; ?>);
</script>
<?php flush(); ?>




